### ISSUE TITLE
Please update to 4.4.0

### ISSUE THREAD

**Issue by tdmoneybanks** [TimHeckel/meteor-bootboxjs#22]
useful for using 
`backdrop: true;`
to close dialog with click on backdrop.

**Comment by CaptSaltyJack** [comment]
Seconded. Though I guess we could just remove this package, and drop the actual bootbox.js file into our Meteor projects.

**Comment by mizzao** [comment]
OK, I pushed 4.4.0. Although as mentioned in makeusabrew/bootbox#402, we should probably just roll this package into bootbox itself and have them publish it.

It's your prerogative whether you want to dump random versions of code into your project. I think it makes things brittle and hard to manage. Might work fine for a quick hack, though.
