### ISSUE TITLE
problem when twbs:bootstrap  upgraded from 3.3.2 to 3.3.4 ?

### ISSUE THREAD

**Issue by yuomtheara** [TimHeckel/meteor-bootboxjs#23]
problem when twbs:bootstrap  upgraded from 3.3.2 to 3.3.4 ?

**Comment by mizzao** [comment]
This is not very informative. What problem?

**Comment by yuomtheara** [comment]
sorry, I can not click any button.

**Comment by thearabbit** [comment]
Now i update to last version, but still don't work.

**Comment by thearabbit** [comment]
Now it is OK.
